name: Build gactar
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        goarch: [amd64, arm64]
        exclude:
          - os: windows-latest
            goarch: arm64

    steps:
      - name: Check out source code
        uses: actions/checkout@master
      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: Build
        run: env GOARCH=${{ matrix.goarch }} make
      - name: Test
        if: ${{ matrix.goarch == 'amd64' }}
        run: go test ./...
