name: Release gactar
on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64

    steps:
      - name: Get repo & tag
        run: |
          echo "RELEASE_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - name: OS darwin
        if: matrix.goos == 'darwin'
        run: echo "OS_NAME=macOS" >> $GITHUB_ENV
      - name: OS not darwin
        if: matrix.goos != 'darwin'
        run: echo "OS_NAME=${{ matrix.goos }}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.28
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          md5sum: false
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          extra_files: doc examples scripts CHANGELOG.md CITATION.cff CONTRIBUTING.md LICENSE README.md
          asset_name: '${REPOSITORY_NAME}-${RELEASE_TAG}-${{ env.OS_NAME }}-${{ matrix.goarch }}'
